### ISSUE TITLE
Inconsistency between the baselines and original paper results

### ISSUE THREAD

**Issue by chenxn2020** [ngl567/CAKE#1]
Hi, I am glad to have read your paper, I am very inspired by your work. However, I have some questions about the experimental results in this paper. 
  In this paper you say that you reproduced the results of baseline (e.g. TransE, RotatE, HAKE) using their source code and recommended parameters, but I notice that the reproduced results are very different from the results in the original paper, and even your own method is lower than the results in the original paper of baselines. Can you explain why? 
 The following table shows the results of the baseline from [HAKE](https://arxiv.org/abs/1911.09419).
![image](https://user-images.githubusercontent.com/68271735/157008213-45ed7e19-b9cb-400c-a04d-a817eaba6895.png)

**Comment by ngl567** [comment]
Thank you for your good question. Actually, you are not the first one to ask me this question. The experimental results are different because the negative sampling size of all the baselines and our proposed model is set as 16 but not 256 or 1024 (used in the original HAKE model) for the consideration of the limitation of memory and efficiency. In our paper, we explain that we aim to illustrate the effectiveness of our developed strategy. I will declare it more clearly in the formal version of the paper.

**Comment by chenxn2020** [comment]
Thank you very much for your reply.  Looking forward to the formal version of the paper and the code
